apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-site-canary
  labels:
    app: personal-site-canary
  namespace: prerelease
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-site-canary
  template:
    metadata:
      labels:
        app: personal-site-canary
      annotations:
        # Consul consult
        consul.hashicorp.com/connect-service: site
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-protocol: "http"
        consul.hashicorp.com/connect-service-port: "8001"
        consul.hashicorp.com/service-meta-sha: canary
        consul.hashicorp.com/service-tags: canary
        # Vault config
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "site"
        vault.hashicorp.com/agent-inject-token: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: personal-site-canary
      serviceAccountName: personal-site-django
      containers:
        - name: app
          image: 7imbrook/site:canary
          imagePullPolicy: Always
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: CONSUL_HTTP_ADDR
              value: $(HOST_IP):8500
            - name: VAULT_ADDR
              value: vault-active:8200
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 100Mi
