#!/bin/sh

echo "Authenticating to consul"

consul login -method consul-consul-k8s-auth-method \
    -token-sink-file ./consul-token \
    -bearer-token-file /var/run/secrets/kubernetes.io/serviceaccount/token;

export CONSUL_HTTP_TOKEN=$(cat ./consul-token)

echo "Registering services in $1";
echo $HOSTNAME

# Populate service template and register
envsubst < /consul/services/service.hcl > service.hcl
consul services register ./service.hcl

# Run consul proxy, because envoy isn't working???
consul connect proxy -sidecar-for $HOSTNAME